name: Learn Workflow

on: 
  push:
    branches: [master]

job:
  setup_django_project:
  runs_on: ubuntu-latest 
  strategy:
    matrix:
      python-version: [3.12]   

  steps:
  - name: checkout code
    uses:actions/checkout@v6  
    - name: setup python ${{matrix.python-version}}
      uses: actions/setup-python@v6
      with:
        python-version: ${{matrix.python-version}}
    - name: install dependencies
      run: pip install -r requirements.txt
    - name: run tests
      run: python manage.py test     